# data
dataset: 'kspon'
dataset_path: ''
transcripts_path: '/home/aiproject/workspace/kosedu/kospeech/data/transcripts.txt'
output_unit: 'character'

# trainer
num_epochs: 10 # default=20
batch_size: 16 # default=32
save_result_every: 1000
checkpoint_every: 5000
print_every: 10
mode: 'train'
seed: 777
resume: False

# device
num_workers: 4
use_cuda: True

# optim default
optimizer: 'adam'
init_lr: 1e-06
final_lr: 1e-06
peak_lr: 1e-03
init_lr_scale: 0.01
final_lr_scale: 0.05
max_grad_norm: 400
warmup_steps: 400
weight_decay: 1e-05
reduction: 'mean'